In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.signal import savgol_filter

from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import mean_squared_error, r2_score

In [65]:
df = pd.read_excel("MTND3.xlsx")
df = df.drop("STT", axis = 1)
df = df.sample(frac=1)
df.head()

,GF,TBS,Natri Benzoate,Abs 260,Abs 262,Abs 264,Abs 266,Abs 268,Abs 270,Abs 272,Abs 274,Abs 276,Abs 278,Abs 280,Abs 282,Abs 284,Abs 286,Abs 288,Abs 290
28,2.5,2.5,2.0,0.283,0.320,0.360,0.403,0.450,0.493,0.522,0.533,0.522,0.495,0.454,0.373,0.262,0.163,0.091,0.048
4,3.0,3.0,1.5,0.283,0.328,0.379,0.431,0.486,0.537,0.576,0.593,0.582,0.554,0.513,0.423,0.298,0.184,0.102,0.052
8,2.0,2.0,1.5,0.219,0.250,0.284,0.320,0.357,0.392,0.417,0.427,0.418,0.397,0.365,0.300,0.211,0.132,0.075,0.041
5,3.0,3.0,1.0,0.263,0.309,0.359,0.412,0.467,0.519,0.558,0.578,0.568,0.541,0.503,0.417,0.293,0.182,0.100,0.050
13,0.5,0.5,0.5,0.081,0.088,0.096,0.105,0.114,0.122,0.128,0.129,0.127,0.121,0.113,0.096,0.074,0.054,0.040,0.032

In [66]:
df_train = df[:int(0.7 * len(df))].values
df_test = df[int(0.7 * len(df)):].values
# df_train
X_train = df_train[:,0:3]
Y_train = df_train[:,3:]
X_test = df_test[:,0:3]
Y_test = df_test[:,3:]

print(Y_test)

[[0.333 0.377 0.426 0.478 0.533 0.584 0.618 0.629 0.615 0.583 0.534 0.436
  0.302 0.186 0.102 0.052]
 [0.231 0.261 0.295 0.329 0.365 0.397 0.419 0.423 0.408 0.384 0.349 0.276
  0.184 0.114 0.069 0.046]
 [0.164 0.171 0.177 0.184 0.194 0.202 0.201 0.194 0.186 0.174 0.151 0.117
  0.084 0.06  0.044 0.035]
 [0.123 0.131 0.14  0.15  0.161 0.171 0.176 0.176 0.173 0.166 0.152 0.129
  0.102 0.077 0.059 0.047]
 [0.124 0.131 0.139 0.146 0.156 0.164 0.166 0.163 0.158 0.15  0.134 0.108
  0.08  0.058 0.042 0.034]
 [0.498 0.6   0.72  0.844 0.965 1.082 1.184 1.242 1.231 1.175 1.108 0.939
  0.669 0.418 0.228 0.11 ]
 [0.115 0.13  0.148 0.165 0.184 0.201 0.214 0.219 0.215 0.205 0.19  0.159
  0.116 0.077 0.05  0.033]
 [0.25  0.289 0.335 0.383 0.433 0.48  0.518 0.539 0.534 0.51  0.48  0.409
  0.3   0.197 0.118 0.069]
 [0.251 0.298 0.349 0.404 0.459 0.512 0.554 0.576 0.567 0.54  0.505 0.421
  0.297 0.185 0.104 0.054]
 [0.153 0.171 0.192 0.214 0.239 0.263 0.284 0.299 0.304 0.298 0.288 0.266
  0.222 0.164 0.112 0.076]
 [0.163 0.19  0.222 0.255 0.289 0.323 0.351 0.369 0.37  0.356 0.337 0.295
  0.225 0.148 0.086 0.044]
 [0.198 0.219 0.243 0.268 0.296 0.322 0.341 0.349 0.348 0.335 0.313 0.271
  0.21  0.145 0.09  0.055]
 [0.188 0.219 0.254 0.29  0.326 0.361 0.388 0.402 0.395 0.375 0.35  0.292
  0.208 0.132 0.078 0.046]
 [0.34  0.379 0.424 0.469 0.519 0.565 0.595 0.606 0.594 0.566 0.519 0.428
  0.308 0.201 0.122 0.073]]

In [67]:
n = 14

In [68]:
pls = PLSRegression(n_components=n)

In [69]:
pls.fit(Y_train, X_train)
X_pred = pls.predict(Y_test)
print(X_pred)
print()
print(X_test)

[[3.17646972 2.82125146 2.21097435]
 [2.25154797 1.04757114 1.16761973]
 [0.42291523 0.44143671 2.29779705]
 [0.31661594 0.86184116 1.4703915 ]
 [0.27250503 0.66770153 1.36118378]
 [7.17181233 6.93728461 0.16122498]
 [1.04685523 1.05677964 0.74197211]
 [2.55249394 3.00497617 0.75411196]
 [3.19495849 2.86738747 0.68614008]
 [0.41415236 2.98922539 0.51910487]
 [1.64296444 2.744318   0.82714742]
 [0.9451381  2.60719763 1.37607335]
 [2.08668227 1.84154171 0.45709703]
 [2.47781911 3.07411844 2.71748959]]

[[3.  3.  3. ]
 [2.5 1.  1. ]
 [0.5 0.5 2.5]
 [0.5 1.  1. ]
 [0.5 0.5 1.5]
 [7.  7.  0. ]
 [1.  1.  0.5]
 [2.5 3.  0.5]
 [3.  3.  0.5]
 [0.5 3.  0.5]
 [1.2 1.5 1. ]
 [1.  2.5 1.5]
 [2.  2.  0.5]
 [2.5 3.  2.5]]

In [70]:
ss = ((X_pred - X_test) / X_test ) * 100
ss

C:\Users\84866\AppData\Local\Temp\ipykernel_6452\767417871.py:1: RuntimeWarning: divide by zero encountered in divide
  ss = ((X_pred - X_test) / X_test ) * 100

array([[  5.88232395,  -5.95828465, -26.3008549 ],
       [ -9.93808103,   4.7571139 ,  16.76197343],
       [-15.41695463, -11.7126573 ,  -8.08811792],
       [-36.67681253, -13.81588388,  47.03915021],
       [-45.49899401,  33.54030686,  -9.25441483],
       [  2.45446191,  -0.89593408,          inf],
       [  4.68552325,   5.67796373,  48.39442126],
       [  2.09975778,   0.16587238,  50.82239104],
       [  6.4986165 ,  -4.4204177 ,  37.22801595],
       [-17.16952801,  -0.35915364,   3.82097308],
       [ 36.9137037 ,  82.95453307, -17.28525759],
       [ -5.48619   ,   4.28790516,  -8.26177672],
       [  4.33411365,  -7.92291474,  -8.58059412],
       [ -0.88723576,   2.4706148 ,   8.69958345]])